"""added tables

Revision ID: 016aaae72a00
Revises: 
Create Date: 2022-08-17 15:21:50.689407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016aaae72a00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
